name: Github CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20.3.1-alpine3.17

    strategy:
      matrix:
        node-version:
          - 20

    steps:
      - name: Github checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm test

      - run: npm run test:ts

      - run: npm audit
